//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "alert")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub alert_type: String,
    #[sea_orm(column_type = "Text")]
    pub alert_message: String,
    pub printer_timestamp: DateTime,
    #[sea_orm(column_type = "Text")]
    pub unique_id: String,
    pub printer_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::printer::Entity",
        from = "Column::PrinterId",
        to = "super::printer::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Printer,
}

impl Related<super::printer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Printer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
