//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "label")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub label_size_id: Uuid,
    pub dpmm: i16,
    #[sea_orm(column_type = "Text")]
    pub zpl: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::history::Entity")]
    History,
    #[sea_orm(
        belongs_to = "super::label_size::Entity",
        from = "Column::LabelSizeId",
        to = "super::label_size::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    LabelSize,
}

impl Related<super::history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::History.def()
    }
}

impl Related<super::label_size::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LabelSize.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
