//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::alert::Entity as Alert;
pub use super::history::Entity as History;
pub use super::label::Entity as Label;
pub use super::label_size::Entity as LabelSize;
pub use super::printer::Entity as Printer;
pub use super::web_link_certificate::Entity as WebLinkCertificate;
