//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::alert::Entity as Alert;
pub use super::history::Entity as History;
pub use super::label::Entity as Label;
pub use super::label_size::Entity as LabelSize;
pub use super::printer::Entity as Printer;
