//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "web_link_certificate")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub certificate_type: String,
    pub issuer_id: Option<Uuid>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", unique)]
    pub serial_number: Vec<u8>,
    #[sea_orm(column_type = "Text")]
    pub public_key: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub private_key: Option<Vec<u8>>,
    pub printer_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
    pub revoked_at: Option<DateTimeWithTimeZone>,
    pub last_ping_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::printer::Entity",
        from = "Column::PrinterId",
        to = "super::printer::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Printer,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::IssuerId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
}

impl Related<super::printer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Printer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
