name: Docker Images

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  images:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Cache target
        uses: Swatinem/rust-cache@v2

      - name: Build binary
        run: cargo build --release

      - name: Move binary
        run: |
          mv target/release/zpl-printer zpl-printer

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: zpl-printer
          path: |
            zpl-printer

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/syfaro/zpl-printer

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
